version: '3.4'

services:
  db:
    image: rest-with-asp-net-udemy-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: India
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: InqudePOC
    ports:
      - 3308:3306
    networks:
      - Inqude
      
  InqudePOC:
    image: InqudePOC
    build:
      context: .
      dockerfile: InqudePOC/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - Inqude
networks:
  Inqude:
    driver: bridge
    
